# This is a basic workflow to help you get started with Actions

name: Metrics

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  schedule: [{cron: '0 0 * * *'}]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  github-metrics:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN  }}
          base: repositories, metadata
          config_timezone: UTC
          #config_display: columns
          #repositories_forks: no
          plugin_introduction: no
          #plugin_introduction_title: no
          plugin_followup: yes
          #plugin_habits: no
          #plugin_lines: no
          plugin_traffic: yes
          #plugin_habits_charts: no
          #plugin_habits_facts: no
          plugin_stargazers: no
          plugin_licenses: yes
          plugin_licenses_ratio: yes
          #plugin_achievements: no
          #plugin_achievements_threshold: A
          #plugin_achievements_secrets: no
          #plugin_achievements_limit: 0    
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 12921102
          plugin_stackoverflow_sections: ''
          plugin_stackoverflow_lines: 2
          plugin_stackoverflow_limit: 1          
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, makefile, qmake, lex, cmake, gnuplot, ipynb
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: no
          #plugin_projects: no
          plugin_isocalendar: yes
